version: '3'
services:
  recepcion_web:
    build: .
    container_name: recepcion_web
    restart: unless-stopped
    entrypoint: java -jar recepcion.jar --db-host 192.168.99.1
    ports:
      - "8001:4567"
